name: Push to Docker registry

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/${{ matrix.arch }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/${{ matrix.arch }}
          cache-from: type=gha
          cache-to: type=gha,node=max
          push: ${{ github.event_name != 'pull_request' }}
          tags: waifu2x:${{ matrix.arch }}
  manifest:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Login to DockerHub
        uses: actions-hub/docker/login@master
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io
      - name: Create manifest
        run: |
          docker manifest create waifu2x:latest waifu2x:amd64 waifu2x:arm64 && \
          docker manifest push waifu2x:latest