name: Push to Docker registry

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
          - arm/v7
        registry:
          - dockerhub
          - github
    steps:
      - name: Create Arch Tag
        run: |
          echo "arch_tag=$(echo "${{ matrix.arch }}"|tr -d '/')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ env.arch_tag }}-${{ github.sha }}
          restore-keys: ${{ github.ref }}-${{ env.arch_tag }}-
      - name: Login to Docker Hub
        if: ${{ matrix.registry == 'dockerhub' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        if: ${{ matrix.registry == 'github' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/${{ matrix.arch }}
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push to Docker Hub
        if: ${{ matrix.registry == 'dockerhub' }}
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/${{ matrix.arch }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/waifu2x:${{ env.arch_tag }}
      - name: Build and Push to GitHub Container Registry
        if: ${{ matrix.registry == 'github' }}
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/${{ matrix.arch }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.actor }}/waifu2x:${{ env.arch_tag }}
  manifest:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        registry:
          - dockerhub
          - github
    steps:
      - name: Login to Docker Hub
        if: ${{ matrix.registry == 'dockerhub' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        if: ${{ matrix.registry == 'github' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Create manifest
        run: |
          if [[ ${{ matrix.registry }} == 'dockerhub' ]]; then
            docker manifest create \
              ${{ secrets.DOCKER_USERNAME }}/waifu2x:latest \
              ${{ secrets.DOCKER_USERNAME }}/waifu2x:amd64 \
              ${{ secrets.DOCKER_USERNAME }}/waifu2x:arm64 \
              ${{ secrets.DOCKER_USERNAME }}/waifu2x:armv7 && \
            docker manifest push ${{ secrets.DOCKER_USERNAME }}/waifu2x:latest
          elif [[ ${{ matrix.registry }} == 'github' ]]; then
            docker manifest create \
              ghcr.io/${{ github.actor }}/waifu2x:latest \
              ghcr.io/${{ github.actor }}/waifu2x:amd64 \
              ghcr.io/${{ github.actor }}/waifu2x:arm64 \
              ghcr.io/${{ github.actor }}/waifu2x:armv7 && \
            docker manifest push ghcr.io/${{ github.actor }}/waifu2x:latest
          fi