name: Push to Docker registry

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
          - arm/v7
    steps:
      - name: Create Arch Tag
        run: |
          echo "arch_tag=$(echo "${{ matrix.arch }}"|tr -d '/')" >> $GITHUB_ENV
      - name: checkout
        uses: actions/checkout@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}-${{ env.arch_tag }}
          restore-keys: ${{ github.ref }}-${{ github.sha }}-${{ env.arch_tag }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/${{ matrix.arch }}
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/${{ matrix.arch }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/waifu2x:${{ env.arch_tag }}
  manifest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create manifest
        run: |
          docker manifest create \
            ${{ secrets.DOCKER_USERNAME }}/waifu2x:latest \
            ${{ secrets.DOCKER_USERNAME }}/waifu2x:amd64 \
            ${{ secrets.DOCKER_USERNAME }}/waifu2x:arm64 \
            ${{ secrets.DOCKER_USERNAME }}/waifu2x:armv7 && \
          docker manifest push ${{ secrets.DOCKER_USERNAME }}/waifu2x:latest